sudo: required
services:
  - docker
env:
  global: #ENV variables
    - SHA=$(git rev-parse HEAD) #get the unique identifier for commit
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 #do not display user input prompts
before_install:
   #unencrypt Service Account
   - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
   #install google sdk, install instance on travis ci instance
   - curl https://sdk.cloud.google.com | bash > /dev/null;
   - source $HOME/google-cloud-sdk/path.bash.inc
   #install kubctl
   - gcloud components update kubectl
   #authorize google cloud
   - gcloud auth activate-service-account --key-file service-account.json
   #set project using unique ID in IAM
   - gcloud config set project master-chariot-287914
   #set compute zone
   - gcloud config set compute/zone us-central1-c
   #what cluster it needs to be working with when issue Kubernetes commands
   - gcloud container clusters get-credentials multi-cluster
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   #build test version
   - docker build -t ctso2/react-test -f ./client/Dockerfile.dev ./client

  script:
    #run Travis CLI test
    - docker run -e CI=true ctso2/docker-react npm test

  #deploy newest images if test successful
  deploy:
    provider: script
    #have to do this from scratch since no built in provide for Kubernetes
    script: bash ./deploy.sh
    on:
      branch: master
